#!/bin/sh

cache_path=~/.cache/egld

# accepted cache interval in seconds
cache_interval=60

# save current timestamp (again, in seconds)
ts=`date +"%s"`

get_price () {
    price=$(curl -s https://www.livecoinwatch.com/price/Elrond-EGLD | grep -Po '<span\s+class="price">\K.*?(?=</span>)' | sed 's/<!-- -->//g')

    if [ $(echo "$price" | grep -E "(Unknown|curl|HTML)" | wc -l) -gt 0 ]; then
        echo "-"
    else
        echo $price
    fi
}

cache_result () {
    echo "$1;$2" > $cache_path
}

# if cache is not present
# write to cache and return result
if ! [[ -f "$cache_path" ]]; then
    temp=$(get_price)
    cache_result $temp $ts
    echo $temp
    exit 1
fi

# read only first line from cached result
read -r line < $cache_path

# split line by ";"
IFS=';' read -ra arr <<< "$line"

# get temp from file
temp="${arr[0]}"

# get diff from timestamps (current and saved)
diff_interval=$((ts - arr[1]))

# echo "Current timestamp"
# echo $ts
#
# echo "Saved timestamp"
# echo ${arr[1]}
#
# echo "Diff timestamp is"
# echo $diff_interval

# check if cache is older than it should
if [[ $diff_interval -gt $cache_interval ]]; then
    # get new price
    temp=$(get_price)

    # save result to cached file
    cache_result $temp $ts
fi

echo $temp
