#!/bin/sh

choice="$(printf "Yes\\nNo" | dmenu -i -p "Reboot?")" || exit 1

[[ $choice == "No" ]] && exit 1

sudo umount ~/Share
sudo umount ~/ParcAuto
sudo pkill openvpn

notify-send "Please wait" "System is rebooting."

sleep 2s

sudo reboot
